Update task.yaml

diff --git a/.tekton/task.yaml b/.tekton/task.yaml
--- a/.tekton/task.yaml
+++ b/.tekton/task.yaml
@@ -17,5 +17,5 @@ spec:
           alive=$(curl -s -o /dev/null -L -w %{http_code} https://cloud.ibm.com);
           if [ "$alive" == "200" ];
           then echo "TEST PASS - 200"; exit 0;
-          else echo "TEST FAIL - $alive"; exit 1;
+          else echo "TEST FAIL - $(alive)"; exit 1;
           fi
