Update task.yaml

diff --git a/.tekton/task.yaml b/.tekton/task.yaml
--- a/.tekton/task.yaml
+++ b/.tekton/task.yaml
@@ -13,11 +13,11 @@ spec:
           echo "Using https://github.com/idsb3t1/KEEP-pipeline-tests-resources.git";
           echo "Endpoint - https://cloud.ibm.com";
           echo "=======================";
-          sleep 10;
+          sleep 60;
           alive=$(curl -s -o /dev/null -L -w %{http_code} https://cloud.ibm.com);
           if [ "$alive" == "200" ];
           then
-            echo "TEST PASS - $(alive)"; exit 0;
+            echo "TEST PASS - $alive"; exit 0;
           else
-            echo "TEST FAIL - $(alive)"; exit 1;
+            echo "TEST FAIL - $alive"; exit 1;
           fi
